name: grpc_vcr
description: Ruby vcr gem implementation for GRPC
version: 1.0.0

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  collection: ^1.16.0
  grpc: ^3.0.2
  json_annotation: ^4.6.0
  mockito: ^5.2.0
  protobuf: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.3.1
  lints: ^1.0.0
  test: ^1.16.0
